import React, { useEffect, useState } from 'react';
import { Check, Eye, FolderTree, Trash2, X } from 'lucide-react';
import { AdminNavbar } from '../../components/admin/AdminNavbar';
import { AdminSidebar } from '../../components/admin/AdminSidebar';
import { Project, ProjectStatus } from '../../types';
import { projectApi } from '../../services/projectApi';
import { ProjectFileTree } from '../../components/projects/ProjectFileTree';
import { ProjectFileViewer } from '../../components/projects/ProjectFileViewer';
import { findProjectFile } from '../../lib/projectSecurity';

export const ManageProjects: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [preview, setPreview] = useState<Project | null>(null);
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const load = () => projectApi.list(false).then(setProjects);
  useEffect(() => { load(); }, []);
  const update = async (project: Project, status: ProjectStatus) => { if (await projectApi.updateStatus(project.id, status)) setProjects((items) => items.map((item) => item.id === project.id ? { ...item, status } : item)); };
  const remove = async (project: Project) => { if (window.confirm(`Delete ${project.name}?`) && await projectApi.delete(project.id)) setProjects((items) => items.filter((item) => item.id !== project.id)); };
  const selected = preview && selectedPath ? findProjectFile(preview.fileTree, selectedPath) : null;
  return <div className="min-h-screen flex bg-slate-50"><AdminSidebar /><div className="flex min-w-0 flex-1 flex-col"><AdminNavbar title="Projects" subtitle="Review safe project submissions and their public file structures" /><main className="flex-1 space-y-6 overflow-y-auto p-6 sm:p-8"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-5 py-3">Project</th><th className="px-4 py-3">Author</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{projects.map((project) => <tr key={project.id}><td className="px-5 py-4"><p className="font-bold text-slate-900">{project.name}</p><p className="text-[11px] text-slate-500">{project.safeFileCount} safe files · {project.technology}</p></td><td className="px-4 py-4 text-slate-600">{project.author}</td><td className="px-4 py-4"><span className="rounded-full border border-slate-200 px-2 py-1 text-[10px] font-bold uppercase text-slate-600">{project.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1.5"><button type="button" onClick={() => { setPreview(project); setSelectedPath(null); }} title="Preview project" className="rounded-lg bg-indigo-50 p-2 text-indigo-700"><Eye className="h-4 w-4" /></button>{project.status === 'pending' && <><button type="button" onClick={() => update(project, 'approved')} title="Approve project" className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><Check className="h-4 w-4" /></button><button type="button" onClick={() => update(project, 'rejected')} title="Reject project" className="rounded-lg bg-amber-50 p-2 text-amber-700"><X className="h-4 w-4" /></button></>}<button type="button" onClick={() => remove(project)} title="Delete project" className="rounded-lg bg-rose-50 p-2 text-rose-700"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></div></main></div>{preview && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4" onClick={() => setPreview(null)}><div className="mx-auto my-8 max-w-6xl rounded-3xl bg-white p-5" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">Safe project preview</p><h2 className="font-display text-2xl font-bold">{preview.name}</h2></div><button type="button" onClick={() => setPreview(null)}><X className="h-5 w-5" /></button></div><div className="grid gap-5 lg:grid-cols-[0.8fr_1.4fr]"><ProjectFileTree files={preview.fileTree} onSelect={(file) => setSelectedPath(file.path)} /><ProjectFileViewer file={selected} onClose={() => setSelectedPath(null)} /></div></div></div>}</div>;
};
